services:
  db:
    image:
      postgres:16.0-alpine3.17
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data

  api:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - TEST_DB_HOST=test_db
    command: >
      sh -c 'alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
    container_name: api
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis

  celery:
    build:
      context: .
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    command:
      celery -A app.tasks.init:celery worker -l INFO
    container_name: celery-worker

  test_db:
    image: postgres:16.0-alpine3.17
    container_name: test_db
    environment:
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - PGPORT=${TEST_DB_PORT}
    ports:
      - "${TEST_DB_PORT}:${TEST_DB_PORT}"

volumes:
  db_volume: