services:
  api:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    container_name: api

  db:
    image:
      postgres:16.0-alpine3.17
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    container_name: redis-insight

  celery:
    build:
      context: .
    env_file:
      - .env
    command:
      celery -A app.tasks.init:celery worker -l INFO
    container_name: celery-worker

  flower:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5555:5555"
    command:
      celery -A app.tasks.init:celery flower
    container_name: flower


volumes:
  db_volume: