services:
  api:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    container_name: api
  db:
    image:
      postgres:16.0-alpine3.17
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data
volumes:
  db_volume: