"""Add date_posted column to comments table

Revision ID: 1de010d38926
Revises: 460a1b9203de
Create Date: 2024-10-19 16:15:02.737952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de010d38926'
down_revision: Union[str, None] = '460a1b9203de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'date_posted')
    # ### end Alembic commands ###
