"""Add date_posted collumn to posts table

Revision ID: 460a1b9203de
Revises: ff1e271b352a
Create Date: 2024-10-19 16:12:12.827975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460a1b9203de'
down_revision: Union[str, None] = 'ff1e271b352a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('post_auto_reply', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('reply_after', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reply_after')
    op.drop_column('users', 'post_auto_reply')
    op.drop_column('posts', 'date_posted')
    # ### end Alembic commands ###
