"""Add is_blocked collumns to posts and comments tables

Revision ID: 67ba27841414
Revises: 1de010d38926
Create Date: 2024-10-22 12:17:00.165973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ba27841414'
down_revision: Union[str, None] = '1de010d38926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_blocked')
    op.drop_column('comments', 'is_blocked')
    # ### end Alembic commands ###
